### ISSUE TITLE
Permissão pra uso

### ISSUE THREAD

**Issue by leitoraincomum** [cationhq/cationbot#11]
Olá, tudo bom?
A Mille me falou que tu tinha feito o bot, queria saber se tem um tutorial pra uso e se posso usar. Sou leiga em bot pra discord.

Atenciosamente,
Fernanda Souza

**Comment by rn4n** [comment]
Oi @leitoraincomum!
Não precisa de permissão, você pode usá-lo como quiser para qualquer propósito.

**TL,DR:** como esse bot foi criado especificamente pro servidor da @mmillecm, algumas configurações estão [_hardcoded_ no código fonte](https://github.com/cationhq/cationbot/blob/development/cationbot/core/roles.py#L4-L37) e podem ser chatas de ter que ficar trocando de servidor para servidor. Eu estou reescrevendo esse bot no meu tempo livre para torná-lo extensível e fácil de ser usado em qualquer lugar. Aliás, se quiser ajudar, sua contribuição será bem-vinda.

----

Para executar esse bot em outro servidor você pode seguir as etapas da sessão "quero contribuir programando" no [CONTRIBUTING](https://github.com/cationhq/cationbot/blob/development/.github/CONTRIBUTING.md#quero-contribuir-programando). Lá tem toda a parte de preparação do ambiente e instalação de dependências, bem como obter o token do Discord para seu bot.

Em seguida você terá que renomear o arquivo [`.env.example`](https://github.com/cationhq/cationbot/blob/development/.env.example) para `env` e editar todas as propriedades que não possuem valor, se precisar de ajuda é só dar um toque.

Por fim, você precisa editar o arquivo [roles.py](https://github.com/cationhq/cationbot/blob/development/cationbot/core/roles.py#L4-L37) para definir todos os cargos que serão atribuídos automaticamente por meio de reações no servidor. Basicamente é `<emoji>:<id do cargo>`. Ex: `"🎮": 829101432330387498`, quando o usuário reagir com o emoji "🎮", automaticamente ele irá receber o cargo de ID 829101432330387498 (que no nosso caso é o "Gamer").

**Comment by leitoraincomum** [comment]
Obrigada pelo retorno Renan, vou olhar com atenção.

Qualquer coisa te chamo.
